name: Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      - run: go test ./...
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: 19489a12fb0b8133760b44d9bb24efd29c6ca58f5418627f2af15e95a86a58d3
        with:
          coverageCommand: go test -coverprofile c.out
          debug: true
          prefix: /home/runner/work/statuspageio/statuspageio/
