name: Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      uses: actions-contrib/go@v0.1.0
    - name: Unit Tests
      run: Go test ./...
