name: Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  Unit-Tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      - run: go test ./...
